FROM debian:bullseye-slim

ARG USERNAME=nonroot
ARG USER_UID=1000
ARG USER_GID=1000

WORKDIR /
ENV DEBIAN_FRONTEND=noninteractive

RUN : \
&& groupadd --gid "${USER_GID}" "${USERNAME}" \
&& useradd --create-home --uid "${USER_UID}" --gid "${USER_GID}" --shell /bin/bash "${USERNAME}" \
&& mkdir -p /etc/sudoers.d/ \
&& echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
&& chmod 0440 /etc/sudoers.d/$USERNAME

USER root
RUN : \
&& apt-get clean \
&& rm -rf /var/lib/apt/lists/*
